apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}

spec:
  type: ClusterIP
  selector:
    app: podinfo
  ports:
    - name: http
      port: {{ .Values.ports.http }}
      protocol: TCP
      targetPort: http
    - port: {{ .Values.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
